version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
      args:
        - TESTNET_API=$TESTNET_API
        - MAINNET_API=$MAINNET_API
    ports:
      - 3000:3000
    environment:
      - PINATA_API_KEY=$PINATA_API_KEY
      - PINATA_SECRET=$PINATA_SECRET
    restart: on-failure
  backend:
    build:
      context: ./backend
    volumes:
      - $MARKETPLACE_PRIVATE_KEY_DIRECTORY:/marketplace
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - IS_TESTNET=$IS_TESTNET
      - SUBMIT_API_BASE_URL=http://cardano-submit-api:8090
      - NFT_BECH32_TAXATION_ADDRESS=$NFT_BECH32_TAXATION_ADDRESS
      - DATABASE_URL=$DATABASE_URL
      - MARKETPLACE_PRIVATE_KEY_FILE=/marketplace/marketplace.skey
    restart: on-failure
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure

  cardano-node:
    image: inputoutput/cardano-node:1.30.1
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - ./db:/data/db
      - node-ipc:/ipc
    restart: on-failure

  cardano-submit-api:
    image: inputoutput/cardano-submit-api:1.30.0
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - node-ipc:/node-ipc
    ports:
      - 8090:8090
    restart: on-failure
  cardano-db-sync:
    image: inputoutput/cardano-db-sync:11.0.4
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-tmp:/tmp
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
    restart: on-failure

volumes:
  node-ipc:
  postgres:
  db-sync-data:
  db-sync-tmp:

secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user