# This is a basic workflow to help you get started with Actions

name: Deploy frontend

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          script_stop: true
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/wottlenft
            git checkout main
            git fetch --all
            git reset --hard origin/main
            cd frontend
            npm install
            export NODE_ENV=production
            npm run build
            pm2 restart wottle --update-env
