# This is a basic workflow to help you get started with Actions

name: Deploy to prod

on:
  push:
    branches: [ deploy ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          port: ${{ secrets.PRODUCTION_PORT }}
          script_stop: true
          script: |
            cd ~/wottlenft
            git checkout deploy
            git fetch --all
            git reset --hard origin/deploy
            docker-compose build backend
            docker-compose build frontend
            docker-compose build profile-backend
            docker-compose up -d frontend backend profile-backend
